### ISSUE TITLE
Performance vignette

### ISSUE THREAD

**Issue by christophe-gouel** [albersonmiranda/fio#41]
Hi,

I stumbled on your package from [Twitter](https://twitter.com/JosiahParry/status/1800621608903602644), and since I am currently working on IO models, it got my interest. After looking at your benchmarking, I am concerned that it is quite deceiving (not on purpose, I am sure).

R is known to be shipped with shitty BLAS libraries (at least on Windows). If I run the same benchmark with optimized BLAS libraries on Windows (instructions: <https://github.com/david-cortes/R-openblas-in-windows>), I do not get any speed gains from Rust. This should be expected as I guess Rust uses the same underlying FORTRAN libraries.

Another issue would be that a lot of matrix operations in R benefit from using the Matrix package (especially for dealing with sparse matrix, which is often important in big IO models, at least the multi-country ones I am used to work with).

Here are some adjustments to your benchmark:
``` R
library(Matrix)

# set seed
set.seed(100)

# data
matrix_dim <- 2000
intermediate_transactions <- matrix(
  as.double(sample(1:1000, matrix_dim^2, replace = TRUE)),
  nrow = matrix_dim,
  ncol = matrix_dim
)
total_production <- matrix(
  as.double(sample(4000000:6000000, matrix_dim, replace = TRUE)),
  nrow = 1,
  ncol = matrix_dim
)

intermediate_transactions_Mat <- as(intermediate_transactions, "Matrix")
total_production_Mat <- as(total_production, "Matrix")

# Base R function
tech_coeff_r <- function(intermediate_transactions, total_production) {
  tech_coeff_matrix <- intermediate_transactions %*% diag(x = 1 / as.vector(total_production))
  return(tech_coeff_matrix)
}

tech_coeff_r_Mat <- function(intermediate_transactions, total_production) {
  tech_coeff_matrix <- intermediate_transactions %*% Diagonal(x = 1 / total_production@x)
  return(tech_coeff_matrix)
}

# {fio} setup
iom_fio <- fio::iom$new("iom", intermediate_transactions, total_production)

# benchmark
benchmark_a <- microbenchmark::microbenchmark(
  fio = fio:::compute_tech_coeff(intermediate_transactions, total_production),
  `Base R` = tech_coeff_r(intermediate_transactions, total_production),
  `Matrix` = tech_coeff_r_Mat(intermediate_transactions_Mat, total_production_Mat),
  leontief = leontief::input_requirement(intermediate_transactions, total_production),
  times = 100
)
print(benchmark_a)

# plot
ggplot2::autoplot(benchmark_a)
```

![image](https://github.com/albersonmiranda/fio/assets/668630/5de05161-ee4a-43ea-a1a0-ccf4c99f2e38)

![image](https://github.com/albersonmiranda/fio/assets/668630/292b58e1-0294-4b24-846d-39ab1817cdf9)

And here is for matrix inversion (in this case, they are no benefits from using Matrix):

``` R
# data
iom_fio$compute_tech_coeff()
technical_coefficients_matrix <- iom_fio$technical_coefficients_matrix
technical_coefficients_Matrix <- as(technical_coefficients_matrix, "Matrix")

# base R function
leontief_inverse_r <- function(technical_coefficients_matrix) {
  dim <- nrow(technical_coefficients_matrix)
  leontief_inverse_matrix <- solve(diag(nrow = dim) - technical_coefficients_matrix)
  return(leontief_inverse_matrix)
}

# Matrix
leontief_inverse_r_Mat <- function(technical_coefficients_matrix) {
  dim <- nrow(technical_coefficients_matrix)
  leontief_inverse_matrix <- solve(diag(nrow = dim) - technical_coefficients_matrix)
  return(leontief_inverse_matrix)
}

# benchmark
benchmark_b <- microbenchmark::microbenchmark(
  fio = fio:::compute_leontief_inverse(technical_coefficients_matrix),
  `Base R` = leontief_inverse_r(technical_coefficients_matrix),
  `Matrix` = leontief_inverse_r_Mat(technical_coefficients_Matrix),
  leontief = leontief::leontief_inverse(technical_coefficients_matrix),
  times = 100
)
print(benchmark_b)

# plot
ggplot2::autoplot(benchmark_b)
```

![image](https://github.com/albersonmiranda/fio/assets/668630/b141dc71-da1a-4775-8f5f-e3e951a00755)

![image](https://github.com/albersonmiranda/fio/assets/668630/0254eeb9-8664-4123-89a8-9d4dfec59e7b)

And for the 3rd example it is even worse for Rust:
![image](https://github.com/albersonmiranda/fio/assets/668630/dd840ae9-4d0c-45fb-92b8-97af8607f35e)

**Comment by albersonmiranda** [comment]
@christophe-gouel thanks for testing! {fio} is just a 1-week old baby and there's a lot of work ahead. There are still other positive aspects that I didn't benchmark yet (such as memory footprint that I expect to be lower thanks to R6 classes).

# SHORT ANSWER

Performance depends on your machine specs and use case (matrix dimensions).

# LONG ANSWER

I don't believe my benchmark is misleading at all since I used a standard installation of R. If I had tweaked things differently from a regular user's setup, then it would have been misleading.

Nonetheless, could you please share your machine specifications? If you look at your means, you'll see they are all slower than {fio}'s in the published benchmark. I used a fairly standard 2018 i5 8GB RAM desktop machine. Even your {leontief} numbers are 10x slower (benchmark_a), and it’s written in C++ Armadillo, so it is expected to be fast (note that Armadillo uses whatever BLAS is registered on your system, so it should benefit from openblas too).

As I mentioned in the fourth paragraph, benchmarks for this kind of code are highly sensitive to machine specifications and matrix dimensions:
>Please note that the results of this benchmarking analysis are dependent on the specific test datasets used and the hardware on which the algorithms were run. Therefore, the results should be interpreted in the context of these specific conditions.

[faer's vs openblas benchmarks](https://faer-rs.github.io/bench-mt.html) already exists and shows that the top-performing library varies depending on matrix dimensions and multi-threading.

Considering the values you've obtained, my guess is that you ran your benchmark in a budget VM (something like a 2-core 4GB setup?). If you run the same benchmark on a 16-core 64GB RAM machine (see the `.devcontainer` folder for Codespaces configuration), you'll find all three implementations executing almost instantaneously and close to each other in performance, with each one being faster depending on the specific benchmark (a, b, or c).

So, it depends! Sometimes one or another implementation will be faster depending on your use case and machine specs.

**Comment by christophe-gouel** [comment]
My machine specifications are: R 4.4.0 with openBLAS on Windows 11 on a 2018 laptop with i7-8665 (4 cores/8 threads) & 32 Go of RAM.

**Comment by christophe-gouel** [comment]
Here is another one from my 10 years old Desktop Workstation on Linux Debian 12 with 16 cores / 32 threads (also R 4.4.0):
![image](https://github.com/albersonmiranda/fio/assets/668630/93e13e3d-f265-42b5-a01d-0d48f7eeaf40)
![image](https://github.com/albersonmiranda/fio/assets/668630/675bfc7c-ebcb-457d-8b67-fb99653af7aa)
![image](https://github.com/albersonmiranda/fio/assets/668630/ea006a15-d492-43f1-ab14-aeb3bd1f1420)
I have done anything specific to BLAS for this machine, but here are the related info:
![image](https://github.com/albersonmiranda/fio/assets/668630/6fd96451-30db-454f-bd0a-04aa08eb6e25)

The benchmarks are closer to yours for fio, but they also show that base R is as comparable to fio and leontief.

So, sure benchmarks differ by machines and configuration, but if you start your documentation with a vignette on benchmarking this is to make a statement : "This improved performance can make a substantial difference in larger analyses". I am sure your package is valuable (and we definitely need good tools for IO analysis not to reprogram everything from scratch every time, which I have been doing for years), but the pure speed does not seem to be main benefit.

**Comment by albersonmiranda** [comment]
Absolutely agree, performance is not the main issue with IO analysis (except when it comes to field of influence; then it's important!). I ran the performance check because if it was slow, there would be no point in keeping the work 😅.

I'll move that disclaimer to the beginning of the vignette and add that performance is not a concern on fast enough machines. I hope that clears things up!

What I'm aiming to do is solve a few issues I've faced when using other packages: ease of use (especially reducing the learning curve for Excel users via the [import add-in](https://albersonmiranda.github.io/fio/reference/fio_addin.html)), clarity of computations (only doing what the user asks), and documentation (functions should clearly state their purpose without the user needing to inspect the code). And, of course, incorporating the latest research (feel free to add an issue for features you haven't seen around). I hope to finish the "Getting Started" vignette next week, highlighting these benefits and a suggested user workflow.

**Comment by christophe-gouel** [comment]
Great!

No, performance can be a real issue with some big MRIO and large structural decomposition analyses, so squeezing the most out of the code is great.

I encourage you to test your code on EXIOBASE and FABIO, which are both huge and really sparse. They required me to improve my code a lot compared to when I was working with WIOD.

I will keep an eye on your package.

Thanks for engaging the discussion!
